routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get('/clear', function () {
    return \Artisan::call('optimize:clear');
});

// Route::get('/', 'HomeController@index');
// Route::get('/service/{slug:slug}', 'ServiceController@single');
// Route::post('contact/ajax_request', 'AjaxController@index')->name('ajax-route');
// Route::get('/blog', 'BlogController@index');
// Route::get('/blog/{slug:slug}', 'BlogController@single');
// Route::get('about', 'AboutController@index');
// Route::get('ourteam', 'OurTeamController@index');
// Route::get('contact', 'ContactController@index');

/**
 * Admin Panel
 */
Route::group(['prefix' => 'rt-panel', 'namespace' => 'administrator', 'as' => 'admin.'], function () {
    Route::get('/logout', 'AuthController@logout')->name('logout');
    Route::post('/login', 'AuthController@login')->name('login.post');
    Route::get('/change_password', 'AuthController@change_password_view')->name('adminchange.password');
    Route::post('/change_password', 'AuthController@change_password');
    Route::get('/', 'DashboardController@index')->name('dashboard');
    Route::group(['middleware' => 'admin'], function () {

        Route::get('event/status/{event}', 'EventController@status')->name('event.status');

        Route::resources([
            'wallet'        => 'WalletController',
            'country'       => 'CountryController',
            'state'         => 'StateController',
            'city'          => 'CityController',

            'language'      => 'LanguageController',
            'religion'      => 'ReligionController',
            'cast'          => 'CastController',
            'gotra'         => 'GotraController',
            'profession'    => 'ProfessionController',
            'meritalstatus' => 'MeritalStatusController',
            'feeling'       => 'FeelingController',
            'role'          => 'RoleController',

            'site'          => 'SiteController',
            'user'          => 'UserController',
            'post'          => 'PostController',
            'place'         => 'PlaceController',
            'event'         => 'EventController',
            'prayer'        => 'PrayerController',
            'tag'           => 'TagController',
        ]);
    });
});

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url('admin/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url('css/agent/style.css') }}">
    <title>Administrator Login</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
</head>

<body>
    <section class="d-flex align-self-center vh-100">
        <div class="LoginBox">
            <div class="card">
                <div class="card-body">
                    <div class="mb-3 text-center">
                        <!-- <img src="{{ url('imgs/logo.png') }}" alt="SN Power Tech" class="mw-100"> -->
                        <h4 class="mw-100">SAMAJ APP</h4>
                    </div>
                    <div id="divSuccessMsg"></div>
                    <form action="{{ route('admin.login.post') }}" method="post" id="agentLoginForm" class="ajax-form">
                        @csrf
                        <div class="form-group">
                            <label for="mobile_no">Mobile</label>
                            <input type="tel" minlength="10" maxlength="10" class="form-control" placeholder="Enter Your Mobile Number" name="mobile" id="mobile_no" required>
                        </div>
                        <button type="submit" class="btn btn-primary btn-block">Send OTP</button>
                    </form>
                </div>
            </div>
        </div>
    </section>

    <script src="{{ url('admin/js/jquery-3.3.1.min.js') }}"></script>
    <script type="module" src="{{ url('js/agent/script.js') }}"></script>
</body>

</html>